### ISSUE TITLE
EventBridge Rules Doesnt Trigger Lambda Function

### ISSUE THREAD

**Issue by SashiDareddy** [aws-samples/s3-to-lambda-patterns#37]
Hi, I was interested in triggering a Lambda function when a file is uploaded to an existing bucket (I use AWS SAM to deploy this application, I'm aware that if S3 & the Lambda function are not created in the same AWS SAM template then it is not possible to trigger the said function from an existing bucket) - so I was interested in your solution having read your [blog](https://aws.amazon.com/blogs/compute/using-dynamic-amazon-s3-event-handling-with-amazon-eventbridge/). 

Steps:
1. I cloned your repo and changed the names for the following parameters: **test-22r4h** as `ExistingBucketName` & **test-22r4h-ct-logs** as `LoggingBucketName` - this is the only change I made in the eventbridge/2-existing-bucket/template.yaml.
2. I create a brand new test bucket in US-East-1 and deployed the application in US-East-1 as well. 
3. After the stack was successfully deployed - I uploaded a test file to my test bucket mentioned above.
4. This correctly triggered a cloud trial log in the S3 bucket ( identified `LoggingBucketName` ).
5. However, the lambda was not triggered. (I waited over 30-mins after I uploaded the file to see if it triggers the lambda).

It looks like something is broken somewhere - I tried in two different accounts and it is the same result. Any help in fixing this is much appreciated. I've attached some screenshots to give you more details:

CloudFormation Stack deployment result:
![image](https://user-images.githubusercontent.com/4083553/145468182-585305ba-0a78-4cd2-8419-14647514c5bd.png)

Lambda Function created from the template with EventBridge trigger:
![image](https://user-images.githubusercontent.com/4083553/145468249-e60307f3-8807-4dda-b8f3-7ed8390486ea.png)

![image](https://user-images.githubusercontent.com/4083553/145468284-d09c8fd2-7364-4c7c-8f4d-d80250554c4b.png)

Event Pattern for EventBridge trigger in full:
```json

{
    "source": [
        "aws.s3"
    ],
    "detail": {
        "requestParameters": {
            "bucketName": [
                "test-22r4h"
            ]
        },
        "eventName": [
            "PutObject"
        ]
    }
}
```
Then uploaded file to my test bucket:
![image](https://user-images.githubusercontent.com/4083553/145468846-7a4a564d-529b-43cc-8ca1-8a3a96362066.png)

Which then correctly triggered the cloud trail:
![image](https://user-images.githubusercontent.com/4083553/145468545-8ff7f844-3c78-4f0d-9e78-06da4110bc98.png)

![image](https://user-images.githubusercontent.com/4083553/145468586-230a7f26-160e-4e29-ba1e-a42b6d0b8e63.png)

**Comment by jbesw** [comment]
Hello! Last week EventBridge announced a new feature, allowing you to consume S3 events directly without the need for CloudTrail. This will reduce the complexity of this configuration and reduce the cost, since you no longer need to pay for the CloudTrail logging.

I'll put a banner on this blog post to alert other readers. In the meantime, take a look at https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/ to see how this works and let me know if you continue to have any issues.

Thanks,
James

**Comment by SashiDareddy** [comment]
Hi James, that sounds amazing - I searched and could'nt find the answer - there is a [CLI way](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-event-notifications-eventbridge.html) to enable EventBridge S3notifications but can this feature be also turned on using CloudFormation/AWS SAM?

**Comment by jbesw** [comment]
Yes, good news! You can do this in SAM like this:

```AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image resizing service

Resources:
  ## S3 bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
        EventBridgeConfiguration: {}
```

**Comment by SashiDareddy** [comment]
Many thanks for the prompt response. I gave this a go & I can see the EventBridge notification being switched on - so this works for new buckets created by the SAM template - but how do we deal with enabling EventBridge Notification setting on existing buckets?  

Edit: I've modified your "eventbridge/2-existing-bucket/template.yaml" to work for new buckets with the notifications set.

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: S3-to-EventBridge Integration - New Buckets Only

Parameters:
  NewBucketName:
    Type: String
    Default: test-22r4h489

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref NewBucketName
      NotificationConfiguration:
        EventBridgeConfiguration: { }

  # Lambda function
  EventConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: eventConsumer/
      Handler: app.handler
      Runtime: nodejs14.x
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref NewBucketName

      Events:
        S3trigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - "Object Created"
              detail:
                bucket:
                  name:
                    - !Ref NewBucketName
```
